var binary = 10101011;
var octal = 375;
var stringg = "kkd";
console.log(stringg);
var bool = true;
console.log(bool);
var nullable = null;
console.log(nullable);
var undefinedval = undefined;
console.log(undefinedval);
var x = 10;
var y = 20;
console.log(x > y ? "x is larger" : "y is larger");
